### ISSUE TITLE
Panel: dialog stacking problem

### ISSUE THREAD

**Issue by philipmarnef** [getkirby/kirby#1126]
I have (custom) field with a pages dialog. It lives in a section in column A. In column B there's a files list, with sort handles. When I open the page select dialog, the sort handles and headline render on top of the dialog, because the dialog is a child of column A. z-index 600 doesn't help because it lives in the stacking context of column A and column B is the next sibling and has a higher z-index.

<img width="869" alt="screen shot 2018-10-23 at 16 31 54" src="https://user-images.githubusercontent.com/1675017/47369444-f8822880-d6e3-11e8-95e4-4ba5ea62123b.png">

**Comment by bastianallgeier** [comment]
You're probably still on a version before the last nightly build. This is already fixed.

**Comment by philipmarnef** [comment]
I'm afraid not. I was on 3.0.0-beta-6.8, and the problem is still there on 3.0.0-beta-6.9.

**Comment by bastianallgeier** [comment]
I'm pretty sure I got it right this time :)
