### ISSUE TITLE
.svg files are not displayed - instead their file url

### ISSUE THREAD

**Issue by flokuek** [getkirby/kirby#1265]
**Describe the bug**

I still experience the problem that .svg files are rendered as their file url. When I select a .jpeg .png instead the file gets displayed correctly. But when I select a .svg file the file url is displayed instead.

Latest version which is working for me is nightly build 3.0.0-beta-6.26

Thanks in advance 😃 

Blueprint:
```
logo:
  label: Logo
  type: files
  multiple: false
```

Template:
```
<?php if($logo = $site->logo()->toFile()): ?>
   <figure role="group">
     <?= $logo ?>
   </figure>
<?php endif ?>
```

**Kirby Version**
tested with latest nightly build 3.0.0-beta-6.31

**Comment by bastianallgeier** [comment]
Yikes, I fixed it in the wrong place. Sorry for that.

**Comment by flokuek** [comment]
So quick ! 😄 have a good weekend!

**Comment by flokuek** [comment]
I still experience the same problems with the latest nightly builds.. Am I doing something wrong?

**Comment by bastianallgeier** [comment]
I somehow managed to fix this in the wrong place two times. I'm pretty sure it's correct now. Sorry!
