### ISSUE TITLE
New Collection from array does not work

### ISSUE THREAD

**Issue by felixbridell** [getkirby/kirby#1429]
**Describe the bug**
new Collection does not work in Kirby 3 like it did in Kirby 2.

This does not work:
```
$selectedProductsCollection = new Collection($selectedProductsArray);
```
But this do work:
```
$selectedProductsCollection = new Kirby\Toolkit\Collection($selectedProductsArray);
```

**Kirby Version**
3.0.0

**Console output**
Error message: “Call to a member function id() on array” inside kirby/src/Cms/Collection.php

**Comment by bastianallgeier** [comment]
✅  This is now fixed on the develop branch thanks to @distantnative

**Comment by o-o-o-o-o** [comment]
I'm still getting this issue migrating a site from Kirby 2 to 3.5

works:
`new Kirby\Toolkit\Collection($chunkCollections);`

does not work (fails silently):
`new Collection($chunkCollections);`

**Comment by afbora** [comment]
@o-o-o-o-o Works as expected on latest version as 3.5.1

````php
$collection = new Collection([
    ['name' => 'John'],
    ['name' => 'Mark'],
    ['name' => 'Jane'],
]);
````

Could you please share how you are trying to add an array?

**Comment by o-o-o-o-o** [comment]
```
/**************************************************	

   * Creates chunks of random size
   *
   * Similar to above but setup as function so it could beused on structured fields
**************************************************/

function randomChunks($col,$min, $max) {
    $temp = clone $col;
    $chunks = [];
  
    ($min >=1 && $min <= $max)? $min=$min:$min=1;
    $max = $max <= $col->count()? $max: $col->count();
    while ($temp->count() > 0) {
      $count = $temp->count();
      $size = mt_rand($min,$max);
      if($count - $size >= $min) {
        array_push($chunks, array_splice($temp->data,0, $size));
      } else {
        array_push($chunks, array_splice($temp->data,0, $count));
      }
  
    }
    $chunkCollections = [];
    foreach($chunks as $items) {
      $collection = clone $col;
      $collection->data = $items;
      $chunkCollections[] = $collection;
    }
    // convert the array of chunks to a collection object
	return new Kirby\Toolkit\Collection($chunkCollections);
	
	//doesn't work
	//return new Collection($chunkCollections);
};
```

**Comment by lukasbestle** [comment]
@o-o-o-o-o What kind of collection is passed to the function as `$col`? Could you please also [enable `debug` mode](https://getkirby.com/docs/guide/troubleshooting/debugging#debug-mode) and post the error message you get when calling your function?

**Comment by o-o-o-o-o** [comment]
@lukasbestle it's an array of files. It's failing silently and returns null.

`  $knickknackItems = $pages->
                    find('knick-knacks')->
                    children()->
                    listed()->
                    first()->
                    slideshow()->toFiles()->
                    shuffle();`

**Comment by lukasbestle** [comment]
I see. The reason is likely that the array items in `$chunkCollections` don't have keys, which is not compatible with the `Kirby\Cms\Collection` class. `Kirby\Toolkit\Collection` is the best fit for your use-case.

You wrote above that it works with the `Kirby\Toolkit\Collection` class. You can use the following code at the top of the file to fix this issue more cleanly:

```php
use Kirby\Toolkit\Collection;
```

It allows you to just use `Collection` in the code like before, which will now refer to the Toolkit Collection class.

Maybe we should have made `Kirby\Toolkit\Collection` the `Collection` alias for better compatibility, but unfortunately that would be a breaking-change now. Sorry that this caused trouble for you!
