### ISSUE TITLE
[Panel] Blurry images in image section

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1520]
**Describe the bug**
We are using an image section limited to a single image in the main column of our page (2/3 width). The layout is set to cards in order to have a large preview of the cover image.

Generally, everything displays as expected but Kirby is loading a small image scaling it up to the needed size which results in a very blurry preview. The source image is 2560 × 1600 pixels.

![grafik](https://user-images.githubusercontent.com/25466/53638519-c13dfe00-3c26-11e9-9f6c-587c23f3b0a0.png)

Setting `size: large` has no effect. The maximum image width seems to be 400 pixels.

**To Reproduce**
Simplified blueprint:

```yml
title: Projekt
sections:
  cover:
    type: files
    headline: Titelbild
    template: cover
    layout: cards
```

**Expected behavior**
The image should not be scalled and display in correct resolution.

**Kirby Version**
Kirby 3.0.3-rc.1 using Firefox on macOS Mojave.

**Comment by distantnative** [comment]
Have you tried `size: huge`?
![75D20A02-FC8B-4570-ADFD-27E6DFB5310F](https://user-images.githubusercontent.com/3788865/57139847-77b58f00-6de0-11e9-983d-24978429f681.jpeg)

Eventually, I guess it would be great to use srcset here. But as fix for now?

**Comment by nilshoerrmann** [comment]
That only seems to affect the size of the grid columns, not the size of the image.

**Comment by distantnative** [comment]
Then something is probably broken cause I think the code above was intended to handle this.

**Comment by texnixe** [comment]
The size `400` for cards layout is hardcoded here:

```
 'data' => function () {
            $data = [];
            if ($this->layout === 'list') {
                $thumb = [
                    'width'  => 100,
                    'height' => 100
                ];
            } else {
                $thumb = [
                    'width'  => 400,
                    'height' => 400
                ];
            }

```
https://github.com/getkirby/kirby/blob/master/config/sections/files.php

Same for files field etc.

**Comment by bastianallgeier** [comment]
✅

**Comment by nilshoerrmann** [comment]
So, I just started testing the latest changes in the `features` branch and the source set works really great for the use case initially described in this issue. But … it doesn't work so well for the small preview thumbs in page and file listings:

<img width="386" alt="grafik" src="https://user-images.githubusercontent.com/25466/58311576-93252000-7e09-11e9-9286-b6bc5285e8b6.png">

While everything looks fine, I was wondering why it took so long for the thumbs to load and noticed that my browser was downloading images with a width of 2000 pixels. That doesn't make sense at all in this scenario where the thumbs size never changes. It would be great to have a separate source set for small thumbs with pixel density description instead of the width descriptions we have now (`1x`, `2x`, maybe `3x`).

I'm testing using Firefox 66.0.5 on latest macOS.

_Pinging @bastianallgeier and @distantnative because I cannot reopen this issue._

**Comment by distantnative** [comment]
We probably should just throw out `srcset` for list items.

**Comment by nilshoerrmann** [comment]
Why that? I'd expect the set to look like this:

```
<img srcset="thumbs-38x38.jpg 1x, thumbs-76x76.jpg 2x" width="38" height="38" />
```

That would define the correct size/density relations.

**Comment by distantnative** [comment]
How would we define those relations for the cards? Those are the sizes we pass as srcset at the moment: 128, 256, 512, 768, 1024, 2048

**Comment by nilshoerrmann** [comment]
For the cards, the widths work just fine in my eyes: the browsers will automatically pick the best match based on display size and screen density. Only the lists need a different set because their width is always fixed. 

Shouldn't this work for the lists:

```php
$image->srcset([
  38 => '1x',
  76 => '2x'
]);
```

**Comment by distantnative** [comment]
✅

**Comment by nilshoerrmann** [comment]
Yay! Thanks!

**Comment by nilshoerrmann** [comment]
Question: Is it a good idea to define `:src="image.url"` which references the full original source? Wouldn't it be better to serve the smallest version here as default?

**Comment by nilshoerrmann** [comment]
Ignore that, just read the full source code …

**Comment by nilshoerrmann** [comment]
Okay, sorry @distantnative, it's me again 👋

The current default source of 128 is too large for the list `srcset`:  the correct sources are never used because the initially loaded image is already larger (128 pixels compared to 38 or 76 pixels). So `image.url` needs to be adjusted for the list to reference the 38 pixel wide preview thumb.

**Comment by distantnative** [comment]
@nilshoerrmann Hiding my lack of knowledge about `srcset` has clearly worked out great 😆  I hope this is now solved.

**Comment by nilshoerrmann** [comment]
Okay, we are nearly there :) There is still an issue I wasn't aware of: Kirby's `srcset` method [doesn't allow for cropping](https://github.com/getkirby/ideas/issues/242) which results in images being to small because they don't fill the full height of the square (in case of landscape images – they are too small in width for portraits). 

Building the `srcset` manually works:

```php
        if ($image = $this->panelImageSource($settings['query'] ?? null)) {
            $modified = '?t=' . $image->modified();

            // for cards
            $settings['cards'] = [
                'url' => $image->thumb([
                    'width' => 128
                ])->url(true) . $modified,
                'srcset' => $image->srcset([
                    128,
                    256,
                    512,
                    768,
                    1024,
                    2048
                ])
            ];

            // for lists
            $squareset = [
                $image->thumb([
                    'width' => 38,
                    'height' => 38,
                    'crop' => 'center'
                ])->url(true),
                $image->thumb([
                    'width' => 76,
                    'height' => 76,
                    'crop' => 'center'
                ])->url(true)
            ];
            $settings['list'] = [
                'url' => $squareset[0] . $modified,
                'srcset' => $squareset[0] . $modified . ' 1x, ' . $squareset[1] . $modified . ' 2x'
            ];

            unset($settings['query']);
        }
```

This most likely doesn't match the Kirby Coding Style™ but it gives the correct result.

**Comment by nilshoerrmann** [comment]
Please note that the url for the cards shouldn't declare a height because we don't want to have that image cropped to a square. The `srcset` values refer to the width so that'll match.

**Comment by nilshoerrmann** [comment]
Ideally, `$image->srcset()` would accept the following:

```php
$image->srcset([
    '1x' => [
        'width' => 38,
        'height' => 38,
        'crop' => 'center'
    ],
    '2x' => [
        'width' => 76,
        'height' => 76,
        'crop' => 'center'
    ]
]);
```

Using the object as options for the `thumb()` method [instead of using the `resize()` method](https://github.com/getkirby/kirby/blob/0885e295788aadac1bd11fbbd28502d3119d2959/src/Cms/FileModifications.php#L127).

**Comment by distantnative** [comment]
@nilshoerrmann let's make that an idea issue since this would involve changing the srcset method quite a bit.

**Comment by nilshoerrmann** [comment]
I added the idea to https://github.com/getkirby/ideas/issues/242.
