### ISSUE TITLE
Error in console when a page with unsaved changes is deleted

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#2251]
**Describe the bug**  
https://forum.getkirby.com/t/error-when-deleting-a-page-with-unsaved-changes/16079

**To Reproduce**  
1. Go to Panel.
2. Make changes in a page without saving.
3. Delete that page without saving changes

**Expected behavior**  
No error should be thrown but the store emptied.

Kirby 3.0.0 rc-2

**Comment by bastianallgeier** [comment]
I cannot reproduce this in rc-2!

**Comment by bastianallgeier** [comment]
Neither in my local dev environment nor in the release download. This issue existed in rc-1. I'm pretty sure it's fixed in rc-2 already.

**Comment by afbora** [comment]
I have fresh test again, still reproduce the issue:

![delete](https://user-images.githubusercontent.com/3393422/67682954-82bd3680-f9a1-11e9-9ff5-a608ccc7a7de.gif)

**Comment by afbora** [comment]
Reuqest order on error:

1.hasChanges()
https://github.com/getkirby/kirby/blob/release/3.3.0/panel/src/components/Forms/FormButtons.vue#L132
2. removeLock()
https://github.com/getkirby/kirby/blob/release/3.3.0/panel/src/components/Forms/FormButtons.vue#L216
3. delete()
https://github.com/getkirby/kirby/blob/release/3.3.0/panel/src/api/request.js#L99
4. post()
https://github.com/getkirby/kirby/blob/release/3.3.0/panel/src/api/request.js#L86
5. request()
https://github.com/getkirby/kirby/blob/release/3.3.0/panel/src/api/request.js#L30

**Comment by bastianallgeier** [comment]
Ok, I'm stupid. I got content locking disabled in my local environment. Sorry! I will test this again.

**Comment by bastianallgeier** [comment]
✅ Pretty sure I got it right this time :)
