### ISSUE TITLE
Uploading an image removes all previously generated thumbnails

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#460]
Moved from here: https://github.com/getkirby/panel/issues/863

**Comment by bastianallgeier** [comment]
Should be fixed.

**Comment by samvantoever** [comment]
@bastianallgeier I just tried to resize a few images upon upload, but all generated thumbs within the page still get deleted when a new one is uploaded.

**Comment by texnixe** [comment]
Have you tested this with the developer version?

**Comment by samvantoever** [comment]
I've tested it with 2.4.1, where can I find the developer version?

**Comment by texnixe** [comment]
https://github.com/getkirby/kirby/tree/develop
https://github.com/getkirby/panel/tree/develop

**Comment by samvantoever** [comment]
Thanks for the information. Just tried it, but the generated thumbnails still get deleted when a new file is uploaded.

**Comment by texnixe** [comment]
Maybe this was only fixed for uploads via the Panel, need to check this.

**Comment by samvantoever** [comment]
I'm uploading the images via drag and drop in the Panel.

**Comment by texnixe** [comment]
Yes, but the thumbs don't get deleted on uploading a new image but on resizing them via the hook, do they?

**Comment by texnixe** [comment]
Reopened, because all thumbs in a page are deleted once a new file is uploaded (tested with developer version).

**Comment by olach** [comment]
Could this issue please be tagged with the milestone 2.4.2 or at least 2.5? :pray:

I'm working on a pretty large and image heavy site and this "bug" is killing the performance of the site. We have editors working daily with the site and it's really frustrating that the thumbs folder is wiped every time a new image is uploaded for no reason.

**Comment by lukasbestle** [comment]
@bastianallgeier How did you fix this on 12 Oct 2016? I can't find the commit.

**Comment by Kallirroi** [comment]
I have the same issue. Anyone?

**Comment by medienbaecker** [comment]
I still have that issue, too. And a fix for it is urgently needed as two separate clients already came to me complaining about the panel being super slow. Uploading an image to any page with more than a few images makes using the panel not very efficient.

To be honest, I am not satisfied with the situation regarding this bug at all. Why is the partial fix (among other things, like the deletable subpages) stuck in the develop branch for months? How are you not frustrated with the thumbnail issue yourself?

Sorry for being so negative about this. I know that you are already working hard on Kirby 3 and other projects, but this situation is slowly killing my passion for Kirby. I think more communication about prioritization and development would help a lot.

**Comment by lukasbestle** [comment]
Sorry for the delay, we can definitely understand your situation. As you can see, this issue is in the milestone for the very next release.

Unfortunately I still have no idea where the "original" fix from 12 Oct 2016 went. @bastianallgeier?
Where did you find a partial fix on the develop branch?

**Comment by nocksock** [comment]
@medienbaecker I did some investigation and potentially found the fix. I'll create a pull request and then let's wait for @bastianallgeier's feedback. So be cautious when applying this fix – definitely test it in a secure environment first.

https://github.com/nocksock/panel/commit/22579726310c22773dbe5d5a158e9937dc8da42a

**Comment by medienbaecker** [comment]
@lukasbestle With "partial fix" I meant this commit: https://github.com/getkirby/panel/commit/a5f6544c1d5ee2c5705cce77236766ddcd362481

@nocksock Thanks a lot for your investigation. I changed the same lines for one website which became unusable. I'm also not sure if this has any disadvantages. I mean the `removeThumbs()` must be there for a reason. Would the `thumbs` folder be more and more crowded after some time?

**Comment by lukasbestle** [comment]
This is now fixed on the Panel develop branch in https://github.com/getkirby/panel/commit/83b4a41b21f9b8ff309c81a8706a524cbf7c7179.

The fix not only preserves other images' thumbs on file uploads, it also applies to file replacements and page renaming.

@medienbaecker and others: Please test the changes and let me know in case there is still an edge-case that doesn't work correctly.

**Comment by medienbaecker** [comment]
I love you, @lukasbestle. This works perfectly, it really improves the overall panel experience greatly!

**Comment by lukasbestle** [comment]
Great to hear that. :)
The release will be out very soon, so it won't be long until everyone will be able to profit from this.
