### ISSUE TITLE
Title accedent clicks

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#521]
It's easy to by accedent click the title when just clicking the gray surface. That's because the title takes up the whole row. It would probably be fine if there was some kind of indication, like a hover effect.

![title](https://user-images.githubusercontent.com/927011/41896746-b577c0f2-7925-11e8-9735-0eef5f7f36c6.gif)

(in the screengif I'm in mobile mode but even in desktop more there is no hover effect)

**Comment by REHvision** [comment]
This happened to me a few times as well :smiley:
I would suggest a light-grey pencil next to the title when hovering it.

**Comment by jenstornell** [comment]
Yes. Other ideas; A white background on hover, maybe with inline-block to limit the space it uses to only make the text clickable, not the whole row.

**Comment by nilshoerrmann** [comment]
This is certainly related to https://github.com/k-next/starterkit/issues/480.

**Comment by bastianallgeier** [comment]
✅ I fixed this by only applying the click to the headline itself and not the entire container and by showing a pencil icon when hovering over the headline.

**Comment by REHvision** [comment]
Although the pencil icon is a great addition, this unortunately is still not solved to my satisfaction yet :sweat_smile:

I accidentially click on the headline too many times and get disrupted for a second ("OH, what happened? What did I do?") until I realize it being the headline again...

I just don't expect this area to be clickable (besides the title with some padding to the right of course).

![bildschirmfoto von 2018-07-10 22-31-59](https://user-images.githubusercontent.com/2584674/42536354-198325ba-8492-11e8-912e-282c1bd05c74.png)

**Comment by bastianallgeier** [comment]
Is that Firefox? In Chrome only the word itself is clickable, which feels pretty good IMHO. I have to double-check that.

**Comment by REHvision** [comment]
Yes Firefox :smile: 
But it's the same in Opera:

![The same in Opera](https://user-images.githubusercontent.com/2584674/42537831-501698ec-8496-11e8-9f75-99df7970504f.png)

It works as expected when I temporarily disable the following CSS-rules for both the `<span>` and the `<i>` inside the `<h1>`: 
```
display: -webkit-box;
display: flex;
```

**Comment by bastianallgeier** [comment]
✅
