### ISSUE TITLE
[Panel] Tab disapears and being replaced by MAIN

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#902]
A really annoying issue.

I have many tabs on a page. When I click to another page and then click back to the page with tabs, all the tabs disapears. It just says "MAIN". Refreshing the page works.

**Steps to reproduce:**

1. Visit the page with tabs inside the panel.
1. Go to another page, in my case with only one tab (which becomes invisible).
1. Go back to the tabs page. The "MAIN" appears.

I use nightly 2018-08-15.

![tabs](https://user-images.githubusercontent.com/927011/44264242-1d5caa00-a222-11e8-8c6d-4505f4b66b04.gif)

**Comment by rasteiner** [comment]
I think this is Vue trying to be smart. 
I'd try fixing it by putting a `:key="$route.fullPath"` on the `router-view` [here](https://github.com/k-next/kirby/blob/master/panel/src/App.vue#L12). Should help.

Or implement the `beforeRouteUpdate` hook on each view component and clean up their `data`.

Bastian probably knows this, but maybe not and in that case it's like 2hrs of "WTF sessions" less.

**Comment by bastianallgeier** [comment]
✅ I think I fixed it. Please let me know after today's nightly build.

**Comment by christianschley** [comment]
I had this bug as well and unfortunately the new nightly version didn't fix it in my case

**Comment by joernroeder** [comment]
i'm having this issue too. as alway up to date via composer 5076900
its not replaced by `Main` in my case but the tabs of the parent page. manually refreshing the page fixes it.

**Comment by joernroeder** [comment]
on another vue project adding the route path as key fixed it. `<router-view :key="$route.path">`
